security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            id: App\Security\User\UserProvider

    role_hierarchy:
        ROLE_RECEPTION: [ROLE_USER]
        ROLE_MANAGER: [ROLE_RECEPTION]
        ROLE_DIRECTOR: [ROLE_MANAGER]
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_DIRECTOR]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            switch_user: true
            form_login:
                login_path: security_login
                check_path: security_login_check
                use_referer: true

#            logout_on_user_change: true
            logout:
                path: security_logout
                target: app_homepage

            guard:
                provider: user_provider
                entry_point: App\Security\FormAuthenticator
                authenticators:
                    - App\Security\FormAuthenticator

            remember_me:
                  secret: '%env(APP_SECRET)%'
                  lifetime: 604800 # 1 week in seconds
                  path: /

#                  Полето на формата което се генерира
#                  remember_me_parameter: !php/const App\Form\LoginType::REMEMBER_ME_FIELD

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/teams-schedule$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/(.+)/schedule$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

