meal_schedule_index:
    path:     /
    controller: App\Controller\MealScheduleController::index
    methods:  GET

meal_schedule_print:
    path:     /print/{id}/{from}/{to}
    controller: App\Controller\MealScheduleController::printTemplate
    methods:  GET



