query_index:
    path:     /
    controller: App\Controller\QueryController::index
    methods:  GET

query_show:
    path:     /{id}/show
    controller: App\Controller\QueryController::show
    methods:  GET

query_new:
    path:     /new
    controller: App\Controller\QueryController::new
    methods:  [GET, POST]

query_edit:
    path:     /{id}/edit
    controller: App\Controller\QueryController::edit
    methods:  [GET, POST]

query_reject:
    path:     /{id}/reject
    controller: App\Controller\QueryController::reject
    methods:  [GET, POST]

query_accept:
    path:     /{id}/accept
    controller: App\Controller\QueryController::accept
    methods:  [GET, POST]

query_payed:
    path:     /{id}/payed
    controller: App\Controller\QueryController::payed
    methods:  [GET, POST]

