query_index:
    path:     /
    controller: App\Controller\QueryController::index
    methods:  GET

query_show:
    path:     /{id}/show
    controller: App\Controller\QueryController::show
    methods:  GET

query_new:
    path:     /new
    controller: App\Controller\QueryController::new
    methods:  [GET, POST]

query_edit:
    path:     /{id}/edit
    controller: App\Controller\QueryController::edit
    methods:  [GET, POST]

query_reject:
    path:     /{id}/reject
    controller: App\Controller\QueryController::reject
    methods:  [GET, POST]

query_accept_form:
    path:     /{id}/accept-form
    controller: App\Controller\QueryController::acceptForm
    methods:  [GET, POST]

query_accept:
    path:     /{id}/accept
    controller: App\Controller\QueryController::accept
    methods:  [GET, POST]

query_in_progress:
    path:     /{id}/in-progress
    controller: App\Controller\QueryController::inProgress
    methods:  [GET, POST]

query_payed:
    path:     /{id}/payed
    controller: App\Controller\QueryController::payed
    methods:  [GET, POST]

query_delete:
    path:     /{id}/delete
    controller: App\Controller\QueryController::delete
    methods:  [GET, POST]

query_print:
    path:     /print/{id}
    controller: App\Controller\QueryController::printTemplate
    methods:  GET

