schedule_index_old:
    path:     /old
    controller: App\Controller\ScheduleController::indexOld
    methods:  GET

schedule_index:
    path:     /
    controller: App\Controller\ScheduleController::index
    methods:  GET

schedule_feed:
    path:     /feed
    controller: App\Controller\ScheduleController::feed
    methods:  [GET, POST]

schedule_print:
    path:     /print/{id}/{from}/{to}
    controller: App\Controller\ScheduleController::printTemplate
    methods:  GET



