schedule_index:
    path:     /
    controller: App\Controller\ScheduleController::index
    methods:  GET

schedule_feed:
    path:     /feed
    controller: App\Controller\ScheduleController::feed
    methods:  [GET, POST]



