#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_user:
    resource: "routes/user.yaml"
    prefix:   /user

app_security:
    resource: "routes/security.yaml"
    prefix:   /user

app_homepage:
    path: /
    controller: App\Controller\DefaultController::index